# This workflow processes any new .md into the output.json and automatically creates a new commit

name: Module.md to JSON

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run JSON creation from .md
        run: npx markdown-json -c settings.json

      # Checks for any changes on the working tree, if there is it will automatically commit
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generated JSON modules file
